Meteor.subscribe 'allUsers'
Meteor.subscribe 'merchants'
Meteor.subscribe 'warehouses'
Meteor.subscribe 'products'
Meteor.subscribe 'productDetails'
Meteor.subscribe 'skulls'
Meteor.subscribe 'providers'
Meteor.subscribe 'myProfile'
Meteor.subscribe 'myMessages'

Meteor.subscribe 'orders'
Meteor.subscribe 'orderDetails'
Meteor.subscribe 'sales'
Meteor.subscribe 'saleDetails'
Meteor.subscribe 'saleExports'
Meteor.subscribe 'deliveries'
Meteor.subscribe 'returns'
Meteor.subscribe 'returnDetails'
Meteor.subscribe 'imports'
Meteor.subscribe 'importDetails'
Meteor.subscribe 'inventories'
Meteor.subscribe 'inventoryDetails'

Meteor.subscribe 'customers'
Meteor.subscribe 'tests'
