Meteor.subscribe 'systems'
Meteor.subscribe 'migrations'
Meteor.subscribe 'myMessages'
Meteor.subscribe 'myNotifications'
Meteor.subscribe 'avatarImages'

Meteor.subscribe 'allUsers'
Meteor.subscribe 'tasks'
Meteor.subscribe 'merchants'
Meteor.subscribe 'warehouses'
Meteor.subscribe 'products'
Meteor.subscribe 'productDetails'
Meteor.subscribe 'productLosts'
Meteor.subscribe 'skulls'
Meteor.subscribe 'providers'
Meteor.subscribe 'myProfile'
Meteor.subscribe 'metroSummaries'

Meteor.subscribe 'orders'
Meteor.subscribe 'orderDetails'
Meteor.subscribe 'sales'
Meteor.subscribe 'saleDetails'
Meteor.subscribe 'saleExports'
Meteor.subscribe 'deliveries'
Meteor.subscribe 'returns'
Meteor.subscribe 'returnDetails'
Meteor.subscribe 'imports'
Meteor.subscribe 'importDetails'
Meteor.subscribe 'inventories'
Meteor.subscribe 'inventoryDetails'

Meteor.subscribe 'customers'
Meteor.subscribe 'tests'

Meteor.subscribe 'transactions'
Meteor.subscribe 'transactionDetails'